Traceback (most recent call last):
  File "c:\Sid\Rutgers\3 Semester\HackHerz\ChalupaCity\Sid\thefile.py", line 12, in <module>
      f = u.urlopen("http://www.google.com/javascript:alert(\" hello world \")")
        File "c:\Anaconda\lib\urllib2.py", line 127, in urlopen
	    return _opener.open(url, data, timeout)
	      File "c:\Anaconda\lib\urllib2.py", line 410, in open
	          response = meth(req, response)
		    File "c:\Anaconda\lib\urllib2.py", line 523, in http_response
		        'http', request, response, code, msg, hdrs)
			  File "c:\Anaconda\lib\urllib2.py", line 448, in error
			      return self._call_chain(*args)
			        File "c:\Anaconda\lib\urllib2.py", line 382, in _call_chain
				    result = func(*args)
				      File "c:\Anaconda\lib\urllib2.py", line 531, in http_error_default
				          raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
					  HTTPError: HTTP Error 400: Bad Request
